### ISSUE TITLE
Camera angle

### ISSUE THREAD

**Issue by hebval** [Slykuiper/IW6X-Movie-Mod#1]
There's an issue when you place your cameras using "sly_cam_node X" : 

The camera angle is not saved. 
The default angle will be the one you're facing before launching the command "sly_cam_mode bezier X".

**Comment by Slykuiper** [comment]
Thanks, fixed!

**Comment by hebval** [comment]
Damnnnn!!! I was about to fix it myself. Was it related to the "player:angles" lines ? I compared it to the S1x .lua file.

**Comment by Slykuiper** [comment]
Yeah.. In iw6x there's an issue with using `player.angles = ` to set the player angles, so I switched it to the player:setplayerangles() function

**Comment by hebval** [comment]
Cool! Thanks for replying and thank you so much for the lovely work

**Comment by hebval** [comment]
Just tested it now and the issue seems to not be fixed. I put a first node looking forward, and a second one looking up to the sky, and when I throw the bezier command, the movement is still fixed to my initial direction...

**Comment by hebval** [comment]
![1](https://user-images.githubusercontent.com/53787149/126689240-1b94407f-46ce-420c-8e2c-f8284fce17a9.png)
![1_cam](https://user-images.githubusercontent.com/53787149/126689242-2ac734bd-c677-430f-a73a-cd494ebde528.png)
![2](https://user-images.githubusercontent.com/53787149/126689244-b34f46e8-de42-46d0-8247-3aacc895999c.png)
![2_cam](https://user-images.githubusercontent.com/53787149/126689247-918c93e6-52dd-433c-9198-64b68549bb8b.png)

As you can see, i'm facing down for the 2nd node, and the camera is still facing straight
