### ISSUE TITLE
Closed issue not fixed

### ISSUE THREAD

**Issue by hebval** [Slykuiper/IW6X-Movie-Mod#2]
Hey dude, sorry but I don't know if you're seeing the messages I'm sending to the closed issue we had yesterday so I'm opening a new one. Just watch the first issue, the angle problem is still not fixed, I've been looking for the whole code and it's too much for me ._.

**Comment by Slykuiper** [comment]
Toko another pass at it and its fixed now!

**Comment by hebval** [comment]
Will check that out tonight, thanks again for your time boss
